function objKeys = saveToDatabase(obj)
    %SAVETODATABASE Saves each HeadphoneType through a database connection.
    %
    %   If there is a duplicate object, this method will return the key of the
    %   original record instead of creating a new object in the Database.
    %
    %   The SqlClient must be connected.
    %
    %Returns:
    %   objKeys (int32): Table Key for the stored HeadphoneType.
    %
    %See also: bose.cnc.meas.HeadphoneType, bose.cnc.datastore.SqlClient,
    %   bose.cnc.meas.HeadphoneType.loadFromDatabase

    % Alex Coleman
    % $Id$

    idHeader = 'bose:cnc:meas:HeadphoneType:';

    sqlClient = bose.cnc.datastore.SqlClient.start;

    storedProcedureName = sprintf('%s.WH.getHeadphoneTypeKey', sqlClient.DatabaseName);

    % Loop over every HeadphoneType given
    objKeys = int32(zeros(numel(obj), 1));

    for indObj = 1:numel(obj)

        if ~obj(indObj).isValid
            warning( ...
                [idHeader 'InvalidHeadphoneType'], ...
                [ ...
                    'This HeadphoneType (%d of %d) was invalid and will ' ...
                    'not be uploaded to the database.' ...
                ], ...
                indObj, ...
                numel(obj) ...
            );
            objKeys(indObj) = int32(0);
            continue
        end

        fetchString = sprintf( ...
            "EXECUTE %s '%s', '%s', '%s', '%s'", ...
            storedProcedureName, ...
            obj(indObj).Name, ...
            obj(indObj).Parent, ...
            obj(indObj).FormFactor.Label, ...
            obj(indObj).Project ...
        );
        %TODO(ALEX): Once we know what errIDs typically pop out of the DB, we can catch them and continue.
        try
            objKeyTable = sqlClient.fetch(fetchString);
            objKey = int32(objKeyTable.HeadphoneTypeKey);
        catch ME

            if strcmp(ME.identifier, 'database:database:JDBCDriverError')
                warning( ...
                    [idHeader 'UploadFailed'], ...
                    [ ...
                        'This HeadphoneType (%d of %d) failed to be ' ...
                        'uploaded. %s' ...
                    ], ...
                    indObj, ...
                    numel(obj), ...
                    sqlClient.Message ...
                );
                objKey = int32(0);
            else
                rethrow(ME);
            end

        end

        objKeys(indObj) = objKey;
        %TODO(ALEX): If an object fails to upload or is invalid, its key will be zero in this array.
    end % For every object to upload

end % saveToDatabase
